package jwhois

var ccSLDs = map[string]string{
	"ae.org":     "whois.centralnic.com",
	"africa.com": "whois.centralnic.com",
	"ar.com":     "whois.centralnic.com",
	"br.com":     "whois.centralnic.com",
	"cn.com":     "whois.centralnic.com",
	"co.com":     "whois.nic.co.com",
	"com.de":     "whois.centralnic.com",
	"de.com":     "whois.centralnic.com",
	"eu.com":     "whois.centralnic.com",
	"eu.org":     "whois.eu.org",
	"gb.com":     "whois.centralnic.com",
	"gb.net":     "whois.centralnic.com",
	"gr.com":     "whois.centralnic.com",
	"hu.com":     "whois.centralnic.com",
	"hu.net":     "whois.centralnic.com",
	"in.net":     "whois.centralnic.com",
	"jp.net":     "whois.centralnic.com",
	"jpn.com":    "whois.centralnic.com",
	"kr.com":     "whois.centralnic.com",
	"mex.com":    "whois.centralnic.com",
	"no.com":     "whois.centralnic.com",
	"qc.com":     "whois.centralnic.com",
	"ro.com":     "whois.centralnic.com",
	"ru.com":     "whois.centralnic.com",
	"sa.com":     "whois.centralnic.com",
	"se.com":     "whois.centralnic.com",
	"se.net":     "whois.centralnic.com",
	"uk.com":     "whois.centralnic.com",
	"uk.net":     "whois.centralnic.com",
	"us.com":     "whois.centralnic.com",
	"us.org":     "whois.centralnic.com",
	"uy.com":     "whois.centralnic.com",
	"za.com":     "whois.centralnic.com",
}
var ccSLDsQueryFormat = map[string]string{}
